<?php

echo '<!DOCTYPE html>
	<html>
	<head>
		<link rel="stylesheet" type="text/css" href="../common/style.css" />
		<script type="text/javascript" src="../assets/bootstrap/js/jquery-3.1.1.min.js"></script>
		<script type="text/javascript" src="../assets/bootstrap/js/bootstrap.js"></script>
		<script type="text/javascript" src="../common/general.js"></script>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	';
	
?>